---
title: "main"
author: "Davide Capone"
date: "22/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("dplyr")
library("ggplot2")
library("tidyverse")
library("tidytext")

```

```{r}
# Import original dataset
dataset <- read.csv("./datasets/tcc_ceds_music.csv")

# Tidying
tidy_dataset <- dataset %>% 
  select(artist_name, 
         track_name, 
         release_date, 
         genre, 
         lyrics, 
         len)

# add coloumn 'decade' to perform analysis
tidy_dataset <- tidy_dataset %>% 
  mutate(decade =
    case_when(
      2010 <= release_date ~ "10-20",
      2000 <= release_date ~ "00-10",
      1990 <= release_date ~ "90-00",
      1980 <= release_date ~ "80-90",
      1970 <= release_date ~ "70-80",
      1960 <= release_date ~ "60-70",
      release_date < 1960 ~ "50-60"
    )
  )

# ... save
write.csv(tidy_dataset, "./datasets/tcc_ceds_music_tidy.csv", row.names = TRUE)

```

```{r}
# Import tidy dataset
tidy_dataset <- data.frame(read.csv("./datasets/tcc_ceds_music_tidy.csv"))
  
```

```{r}
# - 
decades <- c("10-20", "00-10", "90-00", "80-90", "70-80", "60-70", "50-60")

# foreach decade i save their correspondents unigrams, bigrams, trigrams

unigrams_per_decade <- tidy_dataset %>%
  select(lyrics, decade) %>%
  group_by(decade) %>% 
  unnest_tokens(word, lyrics) %>% 
  count(word, sort = TRUE)


nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")

unigrams_per_decade %>%
  filter(decade == "10-20") %>% 
  inner_join(nrc_joy) %>%
  count(word, sort = TRUE)





for (decade in decades) {
  ds <- tidy_dataset %>% 
    select(lyrics) %>% 
    filter(tidy_dataset$decade == decade)
  
  unigram <- ds %>%
    unnest_tokens(word, lyrics) %>% 
    count(word, sort = TRUE)
  
  bigram <- ds %>%
    unnest_tokens(word, lyrics, token = "ngrams", n = 2) %>% 
    count(word, sort = TRUE)
  
  trigram <- ds %>%
    unnest_tokens(word, lyrics, token = "ngrams", n = 3) %>% 
    count(word, sort = TRUE)
  
  write.csv(unigram, paste("./datasets/tokens/unigrams/",decade,".csv"), row.names = TRUE)
  write.csv(bigram, paste("./datasets/tokens/bigrams/",decade,".csv"), row.names = TRUE)
  write.csv(trigram, paste("./datasets/tokens/trigrams/",decade,".csv"), row.names = TRUE)
}


d50_60 <- data.frame(read.csv("./datasets/tokens/unigrams/ 50-60 .csv"))
d70_80 <- data.frame(read.csv("./datasets/tokens/unigrams/ 70-80 .csv"))
d80_90 <- data.frame(read.csv("./datasets/tokens/unigrams/ 80-90 .csv"))
d90_00 <- data.frame(read.csv("./datasets/tokens/unigrams/ 90-00 .csv"))

nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")

d80_90 %>%
  select(word) %>%
  inner_join(nrc_joy) %>%
  count(word, sort = TRUE)


```


